name: AuthLinker
version: '0.0.1'
main: com.miaomc.authLinker.AuthLinker
api-version: '1.16'
authors: [ KumaKorin ]
description: A Minecraft plugin for linking accounts with external services.
website: https://korin.im

commands:
  authlinker:
    description: AuthLinker 主命令
    usage: /authlinker gen <action>
    aliases: [ authlink ]
    permission: miaomc.authlinker.use
  al:
    description: AuthLinker 命令简写
    usage: /al gen <action>
    permission: miaomc.authlinker.use

permissions:
  miaomc.authlinker.use:
    description: 允许使用基本AuthLinker功能
    default: true
  miaomc.authlinker.admin:
    description: 允许使用AuthLinker管理功能
    default: op
    children:
      miaomc.authlinker.use: true