name: AuthLinker
version: '${project.version}'
main: com.miaomc.authLinker.AuthLinker
api-version: '1.17'
authors: [ KumaKorin ]
description: A Minecraft plugin for linking accounts with external services.
website: https://korin.im

commands:
  authlinker:
    description: AuthLinker 主命令
    usage: /authlinker gen <action>
    aliases: [ authlink ]
    permission: miaomc.authlinker.use
  al:
    description: AuthLinker 命令简写
    usage: /al gen <action>

permissions:
  miaomc.authlinker.use:
    description: 允许所有玩家使用 AuthLinker 基本功能
    default: true
